sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails42_haml.gemfile
  - gemfiles/rails50_haml.gemfile
  - gemfiles/rails51_haml.gemfile
  - gemfiles/rails42_boc.gemfile
  - gemfiles/rails50_boc.gemfile
  - gemfiles/rails51_boc.gemfile
  - gemfiles/rack.gemfile
  - gemfiles/rack_boc.gemfile
  - gemfiles/pry09.gemfile
  - gemfiles/pry010.gemfile
  - gemfiles/pry011.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/pry010.gemfile
    - gemfile: gemfiles/pry011.gemfile
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails50_boc.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails50_haml.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails51_boc.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails51_haml.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails50_boc.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails50_haml.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails51_boc.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails51_haml.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails42_boc.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails42_haml.gemfile
